# Telldus Plugs
- platform: "mqtt"
  name: telldus_switch_01_switch
  icon: "mdi:flash"
  state_topic: "zwave2mqtt/telldus_switch_01/37/1/0"
  command_topic: "zwave2mqtt/telldus_switch_01/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: telldus_switch_01_switch
  device: {
    "identifiers": [
        "zwave2mqtt_telldus_switch_01"
      ],
    "manufacturer": "Telldus",
    "model": "313510",
    "name": "TZWP-102 Plug-in Switch",
    "sw_version": "2.11"
  }
- platform: "mqtt"
  name: telldus_switch_02_switch
  icon: "mdi:flash"
  state_topic: "zwave2mqtt/telldus_switch_02/37/1/0"
  command_topic: "zwave2mqtt/telldus_switch_02/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: telldus_switch_02_switch
  device: {
    "identifiers": [
        "zwave2mqtt_telldus_switch_02"
      ],
    "manufacturer": "Telldus",
    "model": "313510",
    "name": "TZWP-102 Plug-in Switch",
    "sw_version": "2.11"
  }
# - platform: "mqtt"
#   name: telldus_switch_03_switch
#   icon: "mdi:flash"
#   state_topic: "zwave2mqtt/telldus_switch_03/37/1/0"
#   command_topic: "zwave2mqtt/telldus_switch_03/37/1/0/set"
#   value_template: "{{value}}"
#   payload_off: "false"
#   payload_on: "true"
#   unique_id: telldus_switch_03_switch
#   device: {
#     "identifiers": [
#         "zwave2mqtt_telldus_switch_03"
#       ],
#     "manufacturer": "Telldus",
#     "model": "313510",
#     "name": "TZWP-102 Plug-in Switch",
#     "sw_version": "2.11"
#   }
- platform: "mqtt"
  name: telldus_switch_04_switch
  icon: "mdi:flash"
  state_topic: "zwave2mqtt/telldus_switch_04/37/1/0"
  command_topic: "zwave2mqtt/telldus_switch_04/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: telldus_switch_04_switch
  device: {
    "identifiers": [
        "zwave2mqtt_telldus_switch_04"
      ],
    "manufacturer": "Telldus",
    "model": "313510",
    "name": "TZWP-102 Plug-in Switch",
    "sw_version": "2.12"
  }
- platform: "mqtt"
  name: telldus_switch_05_switch
  icon: "mdi:flash"
  state_topic: "zwave2mqtt/telldus_switch_05/37/1/0"
  command_topic: "zwave2mqtt/telldus_switch_05/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: telldus_switch_05_switch
  device: {
    "identifiers": [
        "zwave2mqtt_telldus_switch_05"
      ],
    "manufacturer": "Telldus",
    "model": "313510",
    "name": "TZWP-102 Plug-in Switch",
    "sw_version": "2.12"
  }
- platform: "mqtt"
  name: telldus_switch_06_switch
  state_topic: "zwave2mqtt/telldus_switch_06/37/1/0"
  command_topic: "zwave2mqtt/telldus_switch_06/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: telldus_switch_06_switch
  device: {
    "identifiers": [
        "zwave2mqtt_telldus_switch_06"
      ],
    "manufacturer": "Telldus",
    "model": "313510",
    "name": "TZWP-102 Plug-in Switch",
    "sw_version": "2.12"
  }
- platform: "mqtt"
  name: telldus_switch_07_switch
  state_topic: "zwave2mqtt/telldus_switch_07/37/1/0"
  command_topic: "zwave2mqtt/telldus_switch_07/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: telldus_switch_07_light
  device: {
    "identifiers": [
        "zwave2mqtt_telldus_switch_07"
      ],
    "manufacturer": "Telldus",
    "model": "313510",
    "name": "TZWP-102 Plug-in Switch",
    "sw_version": "2.12"
  }
