# Telldus Plugs
- platform: "mqtt"
  name: telldus_switch_01_switch
  icon: "mdi:flash"
  state_topic: "zwave2mqtt/telldus_switch_01/37/1/0"
  command_topic: "zwave2mqtt/telldus_switch_01/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: telldus_switch_01_switch
- platform: "mqtt"
  name: telldus_switch_02_switch
  icon: "mdi:flash"
  state_topic: "zwave2mqtt/telldus_switch_02/37/1/0"
  command_topic: "zwave2mqtt/telldus_switch_02/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: telldus_switch_02_switch
- platform: "mqtt"
  name: telldus_switch_03_switch
  icon: "mdi:flash"
  state_topic: "zwave2mqtt/telldus_switch_03/37/1/0"
  command_topic: "zwave2mqtt/telldus_switch_03/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: telldus_switch_03_switch
- platform: "mqtt"
  name: telldus_switch_04_switch
  icon: "mdi:flash"
  state_topic: "zwave2mqtt/telldus_switch_04/37/1/0"
  command_topic: "zwave2mqtt/telldus_switch_04/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: telldus_switch_04_switch
- platform: "mqtt"
  name: telldus_switch_05_switch
  icon: "mdi:flash"
  state_topic: "zwave2mqtt/telldus_switch_05/37/1/0"
  command_topic: "zwave2mqtt/telldus_switch_05/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: telldus_switch_05_switch
- platform: "mqtt"
  name: telldus_switch_06_switch
  state_topic: "zwave2mqtt/telldus_switch_06/37/1/0"
  command_topic: "zwave2mqtt/telldus_switch_06/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: telldus_switch_06_switch
- platform: "mqtt"
  name: telldus_switch_07_switch
  state_topic: "zwave2mqtt/telldus_switch_07/37/1/0"
  command_topic: "zwave2mqtt/telldus_switch_07/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: telldus_switch_07_light
