# Templates
- platform: template
  switches:
    jain10:
      friendly_name: Jain10
      value_template: "{{ states('binary_sensor.ping_jain10') }}"
      turn_on:
        - service: shell_command.jain10_wake
      turn_off:
        - service: shell_command.jain10_sleep
      icon_template: mdi:power-plug
    srv01:
      friendly_name: Seagate NAS
      value_template: "{{ states('binary_sensor.ping_srv01') }}"
      icon_template: mdi:power-plug
      turn_on:
        - service: shell_command.srv01_wake
      turn_off:
        - service: shell_command.srv01_sleep
