# Trådfri Plugs
- platform: "mqtt"
  name: tradfri_plug_02_power
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_plug_02"
  json_attributes_topic: "zigbee2mqtt/tradfri_plug_02"
  command_topic: "zigbee2mqtt/tradfri_plug_02/set"
  value_template: "{{ value_json.state }}"
- platform: "mqtt"
  name: tradfri_plug_03_power
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_plug_03"
  json_attributes_topic: "zigbee2mqtt/tradfri_plug_03"
  command_topic: "zigbee2mqtt/tradfri_plug_03/set"
  value_template: "{{ value_json.state }}"
- platform: "mqtt"
  name: tradfri_plug_04_power
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_plug_04"
  json_attributes_topic: "zigbee2mqtt/tradfri_plug_04"
  command_topic: "zigbee2mqtt/tradfri_plug_04/set"
  value_template: "{{ value_json.state }}"
- platform: "mqtt"
  name: tradfri_plug_05_power
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_plug_05"
  json_attributes_topic: "zigbee2mqtt/tradfri_plug_05"
  command_topic: "zigbee2mqtt/tradfri_plug_05/set"
  value_template: "{{ value_json.state }}"
- platform: "mqtt"
  name: tradfri_plug_06_power
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_plug_06"
  json_attributes_topic: "zigbee2mqtt/tradfri_plug_06"
  command_topic: "zigbee2mqtt/tradfri_plug_06/set"
  value_template: "{{ value_json.state }}"
- platform: "mqtt"
  name: tradfri_plug_07_power
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_plug_07"
  json_attributes_topic: "zigbee2mqtt/tradfri_plug_07"
  command_topic: "zigbee2mqtt/tradfri_plug_07/set"
  value_template: "{{ value_json.state }}"
- platform: "mqtt"
  name: tradfri_plug_08_power
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_plug_08"
  json_attributes_topic: "zigbee2mqtt/tradfri_plug_08"
  command_topic: "zigbee2mqtt/tradfri_plug_08/set"
  value_template: "{{ value_json.state }}"
- platform: "mqtt"
  name: tradfri_plug_09_power
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_plug_09"
  json_attributes_topic: "zigbee2mqtt/tradfri_plug_09"
  command_topic: "zigbee2mqtt/tradfri_plug_09/set"
  value_template: "{{ value_json.state }}"
- platform: "mqtt"
  name: tradfri_plug_10_power
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_plug_10"
  json_attributes_topic: "zigbee2mqtt/tradfri_plug_10"
  command_topic: "zigbee2mqtt/tradfri_plug_10/set"
  value_template: "{{ value_json.state }}"
