
# Decoration Lights
- alias: Light Mode - Decoration Lights - Night
  id: arnav-jain-se_decoration_lights_off
  trigger:
  - platform: state
    entity_id: switch.ha_lights_mode_night
    to: 'on'
  action:
  - service: switch.turn_off
    data:
      entity_id:
        - switch.tradfri_plug_03_power
        - switch.tradfri_plug_04_power
        - switch.tradfri_plug_05_power
        - switch.tradfri_plug_06_power

- alias: Light Mode - Decoration Lights - Day
  id: arnav-jain-se_decoration_lights_on
  trigger:
  - platform: state
    entity_id: switch.ha_lights_mode_night
    to: 'off'
  action:
  - service: switch.turn_on
    data:
      entity_id:
        - switch.tradfri_plug_03_power
        - switch.tradfri_plug_04_power
        - switch.tradfri_plug_05_power
        - switch.tradfri_plug_06_power



# Lights Mode Time
- alias: Time - Lights Mode - Morning
  id: arnav-jain-se_time_lights_mode_morning
  trigger:
  - platform: time
    at: input_datetime.lights_morning
  - platform: sun
    event: sunrise
  action:
  - service: switch.turn_on
    entity_id: switch.ha_lights_mode_morning
  mode: single


- alias: Time - Lights Mode - Afternoon
  id: arnav-jain-se_time_lights_mode_afternoon
  trigger:
    platform: time
    at: input_datetime.lights_afternoon
  action:
  - service: switch.turn_on
    entity_id: switch.ha_lights_mode_afternoon
  mode: single


- alias: Time - Lights Mode - Evening
  id: arnav-jain-se_time_lights_mode_evening
  trigger:
    platform: time
    at: input_datetime.lights_evening
  action:
  - service: switch.turn_on
    entity_id: switch.ha_lights_mode_evening
  mode: single


- alias: Time - Lights Mode - Night
  id: arnav-jain-se_timer_lights_mode_night
  trigger:
    platform: time
    at: input_datetime.lights_night
  action:
  - service: switch.turn_on
    entity_id: switch.ha_lights_mode_night
  mode: single


# Lights Mode
- alias: Lights Mode - Morning
  id: arnav-jain-se_lights_mode_morning
  mode: single
  trigger:
  - platform: state
    entity_id: switch.ha_lights_mode_morning
    to: 'on'
  action:
  - service: switch.turn_off
    data:
      entity_id:
        # - switch.ha_lights_mode_morning
        - switch.ha_lights_mode_afternoon
        - switch.ha_lights_mode_evening
        - switch.ha_lights_mode_night
  - service: script.light_mode_change
- alias: Lights Mode - Afternoon
  id: arnav-jain-se_lights_mode_afternoon
  mode: single
  trigger:
  - platform: state
    entity_id: switch.ha_lights_mode_afternoon
    to: 'on'
  action:
  - service: switch.turn_off
    data:
      entity_id:
        - switch.ha_lights_mode_morning
        # - switch.ha_lights_mode_afternoon
        - switch.ha_lights_mode_evening
        - switch.ha_lights_mode_night
  - service: script.light_mode_change
- alias: Lights Mode - Evening
  id: arnav-jain-se_lights_mode_evening
  mode: single
  trigger:
  - platform: state
    entity_id: switch.ha_lights_mode_evening
    to: 'on'
  action:
  - service: switch.turn_off
    data:
      entity_id:
        - switch.ha_lights_mode_morning
        - switch.ha_lights_mode_afternoon
        # - switch.ha_lights_mode_evening
        - switch.ha_lights_mode_night
  - service: script.light_mode_change
- alias: Lights Mode - Night
  id: arnav-jain-se_lights_mode_night
  mode: single
  trigger:
  - platform: state
    entity_id: switch.ha_lights_mode_night
    to: 'on'
  action:
  - service: switch.turn_off
    data:
      entity_id:
        - switch.ha_lights_mode_morning
        - switch.ha_lights_mode_afternoon
        - switch.ha_lights_mode_evening
        # - switch.ha_lights_mode_night
  - service: script.light_mode_change


# Disco Lights
- alias: Lights Disco - Bathroom
  id: arnav-jain-se_lights_disco_bathroom
  use_blueprint:
    path: disco_lights.yaml
    input:
      switch_entity: switch.light_disco_bathroom
      light_entity: light.bathroom
      transition_time: '10'
- alias: Lights Disco - Bedroom Bed
  id: arnav-jain-se_lights_disco_bedroom_bed
  use_blueprint:
    path: disco_lights.yaml
    input:
      switch_entity: switch.light_disco_bedroom_bed
      light_entity: light.bedroom_bed
      transition_time: '10'
- alias: Lights Disco - Living Room
  id: arnav-jain-se_lights_disco_living_room
  use_blueprint:
    path: disco_lights.yaml
    input:
      switch_entity: switch.light_disco_livingroom
      light_entity: light.livingroom
      transition_time: '10'


# Common
- alias: Bicycle Battery Charge Complete
  id: arnav-jain-se_battery_charge
  trigger:
  - platform: state
    entity_id: binary_sensor.battery_bicycle_charging
    to: 'off'
  condition:
  - condition: state
    entity_id: switch.telldus_switch_06_switch
    state: 'on'
  action:
  - service: notify.telegram_arnav
    data:
      title: Bicycle Battery
      message: Charging Complete
  - delay:
      minutes: 10
  - service: notify.telegram_arnav
    data:
      title: Bicycle Battery
      message: Turning off charger
  - service: switch.turn_off
    data:
      entity_id: switch.telldus_switch_06_switch


- alias: SRV78 Directory Cleaner
  id: arnav-jain-se_srv78_dir_clean
  trigger:
    platform: time_pattern
    minutes: "/5" # Trigger every 5 minutes
  action:
  - service: shell_command.srv78_dir_clean

# Sensors
- id: '1611599662235'
  alias: Sensor - Door - Store
  description: ''
  use_blueprint:
    path: binary_to_light.yaml
    input:
      motion_entity: binary_sensor.aqara_sensor_switch_01_contact
      target_light: light.store
      no_motion_wait: '0'
- id: '1611599690804'
  alias: Sensor - Motion - Bathroom
  description: ''
  use_blueprint:
    path: binary_to_light.yaml
    input:
      motion_entity: binary_sensor.tradfri_motion_01_occupancy
      target_light: light.bathroom
      no_motion_wait: '0'
- id: '1611603275104'
  alias: Sensor - Motion - Kitchen
  description: ''
  use_blueprint:
    path: binary_to_light.yaml
    input:
      no_motion_wait: '10'
      motion_entity: binary_sensor.smartthings_motion_temp_02_occupancy
      target_light: light.kitchen
- id: '1611603110137'
  alias: Sensor - Motion - Gallery
  description: ''
  use_blueprint:
    path: binary_to_light.yaml
    input:
      no_motion_wait: '10'
      motion_entity: binary_sensor.smartthings_motion_temp_01_occupancy
      target_light: light.gallery

# Timers
- id: '1611604721116'
  alias: Timer - Living Room - On
  description: ''
  use_blueprint:
    path: light_timer_start.yaml
    input:
      light_entity: light.livingroom
      target_timer: timer.livingroom_max
- id: '1611604755633'
  alias: Timer - Living Room - Off
  description: ''
  use_blueprint:
    path: light_timer_finish.yaml
    input:
      light_entity: light.livingroom
      target_timer: timer.livingroom_max

- id: '1611605184590'
  alias: Timer - Study Light - On
  description: ''
  use_blueprint:
    path: light_timer_start.yaml
    input:
      light_entity: light.tradfri_plug_01_light
      target_timer: timer.livingroom_study_max
- id: '1611605184591'
  alias: Timer - Study Light - Off
  use_blueprint:
    path: light_timer_finish.yaml
    input:
      light_entity: light.tradfri_plug_01_light
      target_timer: timer.livingroom_study_max

- id: '1611606188886'
  alias: Timer - Bedroom - On
  description: ''
  use_blueprint:
    path: light_timer_start.yaml
    input:
      light_entity: light.bedroom
      target_timer: timer.bedroom_max
- id: '1611606214670'
  alias: Timer - Bedroom - Off
  description: ''
  use_blueprint:
    path: light_timer_finish.yaml
    input:
      light_entity: light.bedroom
      target_timer: timer.bedroom_max
- id: '1611606359886'
  alias: Timer - Store - On
  description: ''
  use_blueprint:
    path: light_timer_start.yaml
    input:
      light_entity: light.store
      target_timer: timer.store_max
- id: '1611606345967'
  alias: Timer - Store - Off
  description: ''
  use_blueprint:
    path: light_timer_finish.yaml
    input:
      light_entity: light.store
      target_timer: timer.store_max
- id: arnav-jain-se_timer_kitchen_on
  alias: Timer - Kitchen - On
  description: ''
  use_blueprint:
    path: light_timer_start.yaml
    input:
      light_entity: light.kitchen
      target_timer: timer.kitchen_max
- id: arnav-jain-se_timer_kitchen_off
  alias: Timer - Kitchen - Off
  description: ''
  use_blueprint:
    path: light_timer_finish.yaml
    input:
      light_entity: light.kitchen
      target_timer: timer.kitchen_max
- id: arnav-jain-se_timer_gallery_on
  alias: Timer - Gallery - On
  description: ''
  use_blueprint:
    path: light_timer_start.yaml
    input:
      light_entity: light.gallery
      target_timer: timer.gallery_max
- id: arnav-jain-se_timer_gallery_off
  alias: Timer - Gallery - Off
  description: ''
  use_blueprint:
    path: light_timer_finish.yaml
    input:
      light_entity: light.gallery
      target_timer: timer.gallery_max
- id: arnav-jain-se_timer_bathroom_on
  alias: Timer - Bathroom - On
  description: ''
  use_blueprint:
    path: light_timer_start.yaml
    input:
      light_entity: light.bathroom
      target_timer: timer.bathroom_max
- id: arnav-jain-se_timer_bathroom_off
  alias: Timer - Bathroom - Off
  description: ''
  use_blueprint:
    path: light_timer_finish.yaml
    input:
      light_entity: light.bathroom
      target_timer: timer.bathroom_max


## Light Switches
# - id: '1611605747439'
#   alias: Light Switch - Living Room
#   description: ''
#   use_blueprint:
#     path: light_switch.yaml
#     input:
#       light_switch_entity: switch.light_livingroom
#       light_entity: light.livingroom
# - id: '1611605820512'
#   alias: Light Switch - Bathroom
#   description: ''
#   use_blueprint:
#     path: light_switch.yaml
#     input:
#       light_switch_entity: switch.light_bathroom
#       light_entity: light.bathroom
# - id: '1611605844398'
#   alias: Light Switch - Bedroom - Bed
#   description: ''
#   use_blueprint:
#     path: light_switch.yaml
#     input:
#       light_switch_entity: switch.light_bedroom_bed
#       light_entity: light.bedroom_bed
# - id: '1611605930704'
#   alias: Light Switch - Bedroom - Ceiling
#   description: ''
#   use_blueprint:
#     path: light_switch.yaml
#     input:
#       light_switch_entity: switch.light_bedroom_ceiling
#       light_entity: light.bedroom_ceiling
# - id: '1611606272944'
#   alias: Light Switch - Gallery
#   description: ''
#   use_blueprint:
#     path: light_switch.yaml
#     input:
#       light_switch_entity: switch.light_gallery
#       light_entity: light.gallery
# - id: '1611606284135'
#   alias: Light Switch - Kitchen
#   description: ''
#   use_blueprint:
#     path: light_switch.yaml
#     input:
#       light_switch_entity: switch.light_kitchen
#       light_entity: light.kitchen
# - id: '1611606310479'
#   alias: Light Switch - Store
#   description: ''
#   use_blueprint:
#     path: light_switch.yaml
#     input:
#       light_switch_entity: switch.light_store
#       light_entity: light.store
# - id: '1611610011220'
#   alias: Light Switch - Study
#   description: ''
#   use_blueprint:
#     path: light_switch.yaml
#     input:
#       light_switch_entity: switch.light_study
#       light_entity: light.tradfri_plug_01_light
# - id: '1611611216928'
#   alias: Light Switch - Bedroom
#   description: ''
#   mode: single
#   trigger:
#   - platform: state
#     entity_id: switch.light_bedroom
#   action:
#     service: "{% if trigger.to_state.state == \"on\" %}\n  switch.turn_on\n{% else\
#       \ %}\n  switch.turn_off\n{% endif %}\n"
#     data:
#       entity_id:
#       - switch.light_bedroom_bed
#       - switch.light_bedroom_ceiling


# Buttons
- id: '1611608224958'
  alias: Button - Study Light
  description: ''
  use_blueprint:
    path: ikea_2_button.yaml
    input:
      button_entity: sensor.tradfri_button_04_action
      # light_switch_entity: switch.light_study
      light_entity: light.tradfri_plug_01_light
- id: '1611610227692'
  alias: Button - Living Room
  description: ''
  use_blueprint:
    path: ikea_2_button.yaml
    input:
      button_entity: sensor.tradfri_button_01_action
      # light_switch_entity: switch.light_livingroom
      light_entity: light.livingroom
- id: '1611611534011'
  alias: Button - Bedroom - Bed
  description: ''
  use_blueprint:
    path: ikea_2_button.yaml
    input:
      button_entity: sensor.tradfri_button_05_action
      # light_switch_entity: switch.light_bedroom_bed
      light_entity: light.bedroom_bed
- id: '1611611563843'
  alias: Button - Bedroom - Ceiling
  description: ''
  use_blueprint:
    path: ikea_2_button.yaml
    input:
      button_entity: sensor.tradfri_button_06_action
      # light_switch_entity: switch.light_bedroom_ceiling
      light_entity: light.bedroom_ceiling




# Alarm
# Set Next Alarm
- alias: DateTime - Alarm set on Mobile
  id: arnav-jain-se_datetime_alarm_mobile
  trigger:
  - platform: state
    entity_id:
      - input_datetime.next_alarm_manual
      - input_datetime.next_alarm_zr
      - input_datetime.next_alarm_a3
      - input_datetime.next_alarm_g6
  condition:
    - condition: template
      value_template: "{{ as_timestamp(states(trigger.entity_id)) > as_timestamp(now())}}"
  action:
  - service: script.set_alarm


# Set Pre Trigger
- alias: DateTime - Alarm Set
  id: arnav-jain-se_datetime_alarm_set
  trigger:
  - platform: state
    entity_id:
    - input_datetime.next_alarm
    - input_number.alarm
  action:
    - service: input_datetime.set_datetime
      data:
        entity_id: input_datetime.next_alarm_light
        timestamp: "{{ state_attr('input_datetime.next_alarm', 'timestamp') | int - (states('input_number.alarm')| int) *60 | int}}"

# Run Wake Up Lights
- alias: DateTime - Alarm Run
  id: arnav-jain-se_datetime_alarm_run
  trigger:
  - platform: time
    at: input_datetime.next_alarm_light
  condition:
    - condition: state
      entity_id: switch.morning_alarm_arm
      state: 'on'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.morning_alarm_arm
    - service: script.lights_wake_up
      data:
        light: light.bedroom
