#  Switches
- platform: "mqtt"
  name: fibaro_switch_02_switch
  state_topic: "zwave2mqtt/fibaro_switch_02/37/1/0"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: fibaro_switch_02_switch
  device: {
    "identifiers": [
        "zwave2mqtt_fibaro_switch_02"
      ],
      "manufacturer": "FIBARO System",
      "model": "0x1001",
      "name": "FGWPE/F Wall Plug Gen5",
      "sw_version": "3.02"
  }
- platform: "mqtt"
  name: telldus_switch_03_switch
  state_topic: "zwave2mqtt/telldus_switch_03/37/1/0"
  # command_topic: "zwave2mqtt/telldus_switch_03/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: telldus_switch_03_switch
  device: {
    "identifiers": [
        "zwave2mqtt_telldus_switch_03"
      ],
    "manufacturer": "Telldus",
    "model": "313510",
    "name": "TZWP-102 Plug-in Switch",
    "sw_version": "2.11"
  }

# Door Sensors
- platform: "mqtt"
  name: aqara_sensor_switch_01_contact
  state_topic: "zigbee2mqtt/aqara_sensor_switch_01"
  json_attributes_topic: "zigbee2mqtt/aqara_sensor_switch_01"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: false
  payload_off: true
  value_template: "{{ value_json.contact }}"
  device_class: "door"

# Motion Sensors
- platform: "mqtt"
  name: smartthings_motion_temp_01_occupancy
  state_topic: "zigbee2mqtt/smartthings_motion_temp_01"
  json_attributes_topic: "zigbee2mqtt/smartthings_motion_temp_01"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.occupancy }}"
  device_class: "motion"
- platform: "mqtt"
  name: smartthings_motion_temp_01_occupancy_delayed
  state_topic: "hass/sensors/smartthings_motion_temp_01"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.occupancy }}"
  device_class: "motion"
- platform: "mqtt"
  name: smartthings_motion_temp_02_occupancy
  state_topic: "zigbee2mqtt/smartthings_motion_temp_02"
  json_attributes_topic: "zigbee2mqtt/smartthings_motion_temp_02"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.occupancy }}"
  device_class: "motion"
- platform: "mqtt"
  name: smartthings_motion_temp_02_occupancy_delayed
  state_topic: "hass/sensors/smartthings_motion_temp_02"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.occupancy }}"
  device_class: "motion"
- platform: "mqtt"
  name: tradfri_motion_01_occupancy
  state_topic: "zigbee2mqtt/tradfri_motion_01"
  json_attributes_topic: "zigbee2mqtt/tradfri_motion_01"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.occupancy }}"
  device_class: "motion"

# Templates
- platform: template
  sensors:
    aeotec_sensor6_01_motion:
      device_class: motion
      value_template: "{{ states('sensor.aeotec_sensor6_01_motion_vibration') | int == 8}}"
    aeotec_sensor6_01_vibration:
      device_class: vibration
      value_template: "{{ states('sensor.aeotec_sensor6_01_motion_vibration') | int == 3}}"

# Connected Devices
- platform: ping
  host: RT242.jain.lan
  name: ping_asus_router242
  count: 1
  scan_interval: 30
- platform: ping
  host: nas83.jain.lan
  name: ping_nas83
  count: 1
  scan_interval: 30
- platform: ping
  host: jain56.jain.lan
  name: ping_jain56
  count: 1
- platform: ping
  host: docker56.jain.lan
  name: ping_docker56
  count: 1

- platform: ping
  host: jain10.jain.lan
  name: ping_jain10
  count: 1
  scan_interval: 30
- platform: ping
  host: jain70.jain.lan
  name: ping_jain70
  count: 1
- platform: ping
  host: stolx0831.jain.lan
  name: ping_sas_stolx0831
  count: 1

- platform: ping
  host: octopi.jain.lan
  name: ping_octopi
  count: 1
- platform: ping
  host: ha-bridge.jain.lan
  name: ping_raspberrypi_ha_bridge
  count: 1
- platform: ping
  host: raspberrypi.jain.lan
  name: ping_raspberrypi
  count: 1

- platform: ping
  host: MotoG6Plus.jain.lan
  name: ping_motorola_g6_plus
  count: 1
- platform: ping
  host: XperiaZR.jain.lan
  name: ping_sony_xperia_zr
  count: 1
- platform: ping
  host: Tablet35.jain.lan
  name: ping_asus_a810
  count: 1
- platform: ping
  host: nexus10.jain.lan
  name: ping_google_nexus_10
  count: 1
- platform: ping
  host: Kindle65.jain.lan
  name: ping_amazon_kindle_fire_7
  count: 1

- platform: ping
  host: ChromeAudioBedroom.jain.lan
  name: ping_chromecast_audio_bedroom
  count: 1
- platform: ping
  host: ChromeAudioLivingroom.jain.lan
  name: ping_chromecast_audio_livingroom
  count: 1
- platform: ping
  host: Cast50.jain.lan
  name: ping_chromecast_video
  count: 1

# Zigbee Updates
- platform: template
  sensors:
# Plugs
    tradfri_plug_01_update:
      value_template: "{{ state_attr('light.tradfri_plug_01_light', 'update_available') }}"
    tradfri_plug_02_update:
      value_template: "{{ state_attr('switch.tradfri_plug_02_power', 'update_available') }}"
# Remotes
    tradfri_switch_01_update:
      value_template: "{{ state_attr('sensor.tradfri_switch_01_action', 'update_available') }}"
    tradfri_switch_02_update:
      value_template: "{{ state_attr('sensor.tradfri_switch_02_action', 'update_available') }}"
    tradfri_button_01_update:
      value_template: "{{ state_attr('sensor.tradfri_button_01_action', 'update_available') }}"
    tradfri_button_02_update:
      value_template: "{{ state_attr('sensor.tradfri_button_02_action', 'update_available') }}"
# Door Sensors
# N/A
# Motion Sensors
    tradfri_motion_01_update:
      value_template: "{{ state_attr('binary_sensor.tradfri_motion_01', 'update_available') }}"
# Lights
# RGB Lights
    tradfri_led_rgb_01_update:
      value_template: "{{ state_attr('light.tradfri_led_rgb_01_light', 'update_available') }}"
    tradfri_led_rgb_02_update:
      value_template: "{{ state_attr('light.tradfri_led_rgb_02_light', 'update_available') }}"
    tradfri_led_rgb_03_update:
      value_template: "{{ state_attr('light.tradfri_led_rgb_03_light', 'update_available') }}"
    tradfri_led_rgb_04_update:
      value_template: "{{ state_attr('light.tradfri_led_rgb_04_light', 'update_available' ) }}"
# White Lights
    tradfri_led_white_01_update:
      value_template: "{{ state_attr('light.tradfri_led_white_01_light', 'update_available') }}"
    tradfri_led_white_02_update:
      value_template: "{{ state_attr('light.tradfri_led_white_02_light', 'update_available') }}"
    tradfri_led_white_03_update:
      value_template: "{{ state_attr('light.tradfri_led_white_03_light', 'update_available') }}"
# GU10 Lights
    tradfri_led_gu10_01_update:
      value_template: "{{ state_attr('light.tradfri_led_gu10_01_light', 'update_available') }}"
    tradfri_led_gu10_02_update:
      value_template: "{{ state_attr('light.tradfri_led_gu10_02_light', 'update_available') }}"
    tradfri_led_gu10_03_update:
      value_template: "{{ state_attr('light.tradfri_led_gu10_03_light', 'update_available') }}"
    tradfri_led_gu10_04_update:
      value_template: "{{ state_attr('light.tradfri_led_gu10_04_light', 'update_available') }}"
    tradfri_led_gu10_05_update:
      value_template: "{{ state_attr('light.tradfri_led_gu10_05_light', 'update_available') }}"
    tradfri_led_gu10_06_update:
      value_template: "{{ state_attr('light.tradfri_led_gu10_06_light', 'update_available') }}"
