---
version: "2.4"
services:

    hass:
        image: homeassistant/home-assistant:2021.1.4
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Stockholm
        volumes:
            - W:\.DockerConfig\hass:/config
        ports:
            - 8123:8123
        logging:
                driver: "json-file"
                options:
                    max-size: "200k"
                    max-file: "10"

    coder:
        image: codercom/code-server:3.4.1
        # build: .
#        restart: on-failure
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Stockholm
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - .:/home/coder/project
            - ./.coder:/home/coder/.local/share/code-server
        ports:
            - 9313:8080
#        expose:
        command: --auth none
