# White E27
- platform: "mqtt"
  name: tradfri_led_white_01_light
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_led_white_01"
  command_topic: "zigbee2mqtt/tradfri_led_white_01/set"
  brightness: true
  color_temp: true
  schema: "json"
- platform: "mqtt"
  name: tradfri_led_white_02_light
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_led_white_02"
  command_topic: "zigbee2mqtt/tradfri_led_white_02/set"
  brightness: true
  color_temp: true
  schema: "json"
- platform: "mqtt"
  name: tradfri_led_white_03_light
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_led_white_03"
  command_topic: "zigbee2mqtt/tradfri_led_white_03/set"
  brightness: true
  color_temp: true
  schema: "json"
# White GU10
- platform: "mqtt"
  name: tradfri_led_gu10_01_light
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_led_gu10_01"
  command_topic: "zigbee2mqtt/tradfri_led_gu10_01/set"
  brightness: true
  color_temp: true
  schema: "json"
- platform: "mqtt"
  name: tradfri_led_gu10_02_light
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_led_gu10_02"
  command_topic: "zigbee2mqtt/tradfri_led_gu10_02/set"
  brightness: true
  color_temp: true
  schema: "json"
- platform: "mqtt"
  name: tradfri_led_gu10_03_light
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_led_gu10_03"
  command_topic: "zigbee2mqtt/tradfri_led_gu10_03/set"
  brightness: true
  color_temp: true
  schema: "json"
- platform: "mqtt"
  name: tradfri_led_gu10_04_light
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_led_gu10_04"
  command_topic: "zigbee2mqtt/tradfri_led_gu10_04/set"
  brightness: true
  color_temp: true
  schema: "json"
- platform: "mqtt"
  name: tradfri_led_gu10_05_light
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_led_gu10_05"
  command_topic: "zigbee2mqtt/tradfri_led_gu10_05/set"
  brightness: true
  color_temp: true
  schema: "json"
- platform: "mqtt"
  name: tradfri_led_gu10_06_light
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_led_gu10_06"
  command_topic: "zigbee2mqtt/tradfri_led_gu10_06/set"
  brightness: true
  color_temp: true
  schema: "json"
# RGB E27
- platform: "mqtt"
  name: tradfri_led_rgb_01_light
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_led_rgb_01"
  command_topic: "zigbee2mqtt/tradfri_led_rgb_01/set"
  brightness: true
  xy: true
  schema: "json"
- platform: "mqtt"
  name: tradfri_led_rgb_02_light
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_led_rgb_02"
  command_topic: "zigbee2mqtt/tradfri_led_rgb_02/set"
  brightness: true
  xy: true
  schema: "json"
- platform: "mqtt"
  name: tradfri_led_rgb_03_light
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_led_rgb_03"
  command_topic: "zigbee2mqtt/tradfri_led_rgb_03/set"
  brightness: true
  xy: true
  schema: "json"


# Plugs
- platform: "mqtt"
  name: tradfri_plug_01_light
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_plug_01"
  command_topic: "zigbee2mqtt/tradfri_plug_01/set"
  schema: "json"
- platform: "mqtt"
  name: telldus_switch_06_light
  state_topic: "zwave2mqtt/telldus_switch_06/37/1/0"
  command_topic: "zwave2mqtt/telldus_switch_06/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: telldus_switch_06_switch
  device: {
    "identifiers": [
        "zwave2mqtt_telldus_switch_06"
      ],
    "manufacturer": "Telldus",
    "model": "313510",
    "name": "TZWP-102 Plug-in Switch",
    "sw_version": "2.12"
  }
- platform: "mqtt"
  name: telldus_switch_07_light
  state_topic: "zwave2mqtt/telldus_switch_07/37/1/0"
  command_topic: "zwave2mqtt/telldus_switch_07/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: telldus_switch_07_light
  device: {
    "identifiers": [
        "zwave2mqtt_telldus_switch_07"
      ],
    "manufacturer": "Telldus",
    "model": "313510",
    "name": "TZWP-102 Plug-in Switch",
    "sw_version": "2.12"
  }


# Groups
- platform: group
  name: all
  entities:
    - light.bathroom
    - light.bedroom
    - light.gallery
    - light.kitchen
    - light.livingroom
    - light.store
- platform: group
  name: bathroom
  entities:
  - light.tradfri_led_rgb_03_light
- platform: group
  name: bedroom
  entities:
  - light.bedroom_ceiling
  - light.bedroom_bed
  - light.telldus_switch_07_light
- platform: "mqtt"
  name: bedroom_ceiling
  state_topic: "zigbee2mqtt/lights_bedroom_ceiling"
  availability_topic: "zigbee2mqtt/bridge/state"
  command_topic: "zigbee2mqtt/lights_bedroom_ceiling/set"
  brightness: true
  color_temp: true
  schema: "json"
- platform: "mqtt"
  name: bedroom_bed
  state_topic: "zigbee2mqtt/lights_bedroom_bed"
  availability_topic: "zigbee2mqtt/bridge/state"
  command_topic: "zigbee2mqtt/lights_bedroom_bed/set"
  brightness: true
  xy: true
  schema: "json"
- platform: "mqtt"
  name: gallery
  state_topic: "zigbee2mqtt/lights_gallery"
  availability_topic: "zigbee2mqtt/bridge/state"
  command_topic: "zigbee2mqtt/lights_gallery/set"
  brightness: true
  color_temp: true
  schema: "json"
- platform: "mqtt"
  name: kitchen
  state_topic: "zigbee2mqtt/lights_kitchen"
  availability_topic: "zigbee2mqtt/bridge/state"
  command_topic: "zigbee2mqtt/lights_kitchen/set"
  brightness: true
  color_temp: true
  schema: "json"
- platform: group
  name: livingroom
  entities:
  - light.tradfri_plug_01_light
  - light.telldus_switch_06_light
- platform: group
  name: store
  entities:
  - light.tradfri_led_white_03_light

