# Wake On LAN
# - platform: wake_on_lan
#   mac_address: "F8-32-E4-86-7F-BF"
#   name: "Jain10 WOL"
#   host: "jain10.jain.lan"
#   broadcast_address: "192.168.8.255"


# Power
- platform: "mqtt"
  name: fibaro_switch_01_switch
  icon: "mdi:flash"
  state_topic: "zwave2mqtt/fibaro_switch_01/37/1/0"
  command_topic: "zwave2mqtt/fibaro_switch_01/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: fibaro_switch_01_switch
  device: {
    "identifiers": [
        "zwave2mqtt_fibaro_switch_01"
      ],
      "manufacturer": "FIBARO System",
      "model": "0x1001",
      "name": "FGWPE/F Wall Plug Gen5",
      "sw_version": "3.02"
  }
- platform: "mqtt"
  name: telldus_switch_01_switch
  icon: "mdi:flash"
  state_topic: "zwave2mqtt/telldus_switch_01/37/1/0"
  command_topic: "zwave2mqtt/telldus_switch_01/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: telldus_switch_01_switch
  device: {
    "identifiers": [
        "zwave2mqtt_telldus_switch_01"
      ],
      "manufacturer": "Telldus",
      "model": "313510",
      "name": "TZWP-102 Plug-in Switch",
      "sw_version": "2.11"
  }
- platform: "mqtt"
  name: telldus_switch_02_switch
  icon: "mdi:flash"
  state_topic: "zwave2mqtt/telldus_switch_02/37/1/0"
  command_topic: "zwave2mqtt/telldus_switch_02/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: telldus_switch_02_switch
  device: {
    "identifiers": [
        "zwave2mqtt_telldus_switch_02"
      ],
      "manufacturer": "Telldus",
      "model": "313510",
      "name": "TZWP-102 Plug-in Switch",
      "sw_version": "2.11"
  }


# Light Controls
- platform: "mqtt"
  name: ha_lights_manual_control
  state_topic: "hass/lights/manual-control"
  command_topic: "hass/lights/manual-control"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"

- platform: "mqtt"
  name: ha_lights_mode_morning
  state_topic: "hass/lights/mode/morning"
  command_topic: "hass/lights/mode"
  value_template: "{{value}}"
  state_on: "true"
  state_off: "false"
  payload_on: "morning"
  retain: "on"

- platform: "mqtt"
  name: ha_lights_mode_afternoon
  state_topic: "hass/lights/mode/afternoon"
  command_topic: "hass/lights/mode"
  value_template: "{{value}}"
  state_on: "true"
  state_off: "false"
  payload_on: "afternoon"
  retain: "on"

- platform: "mqtt"
  name: ha_lights_mode_evening
  state_topic: "hass/lights/mode/evening"
  command_topic: "hass/lights/mode"
  value_template: "{{value}}"
  state_on: "true"
  state_off: "false"
  payload_on: "evening"
  retain: "on"

- platform: "mqtt"
  name: ha_lights_mode_night
  state_topic: "hass/lights/mode/night"
  command_topic: "hass/lights/mode"
  value_template: "{{value}}"
  state_on: "true"
  state_off: "false"
  payload_on: "night"
  retain: "on"
