- platform: wake_on_lan
  mac_address: "F8-32-E4-86-7F-BF"
  name: "Jain10 WOL"
  host: "jain10.jain.lan"
  broadcast_address: "192.168.8.255"

- platform: "mqtt"
  name: fibaro_switch_01_switch
  icon: "mdi:flash"
  state_topic: "zwave2mqtt/fibaro_switch_01/37/1/0"
  command_topic: "zwave2mqtt/fibaro_switch_01/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: fibaro_switch_01_switch
  device: {
    "identifiers": [
        "zwave2mqtt_fibaro_switch_01"
      ],
      "manufacturer": "FIBARO System",
      "model": "0x1001",
      "name": "FGWPE/F Wall Plug Gen5",
      "sw_version": "3.02"
  }

- platform: "mqtt"
  name: ha_lights_manual_control
  state_topic: "hass/lights/manual-control"
  command_topic: "hass/lights/manual-control"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"

