# Wake On LAN
# - platform: wake_on_lan
#   mac: "F8-32-E4-86-7F-BF" -- Change in 0.103
#   name: "Jain10 WOL"
#   host: "jain10.jain.lan"
#   broadcast_address: "192.168.8.255"


# Power
- platform: "mqtt"
  name: tradfri_plug_02_power
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_plug_02"
  json_attributes_topic: "zigbee2mqtt/tradfri_plug_02"
  command_topic: "zigbee2mqtt/tradfri_plug_02/set"
  value_template: "{{ value_json.state }}"
- platform: "mqtt"
  name: tradfri_plug_03_power
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_plug_03"
  json_attributes_topic: "zigbee2mqtt/tradfri_plug_03"
  command_topic: "zigbee2mqtt/tradfri_plug_03/set"
  value_template: "{{ value_json.state }}"
- platform: "mqtt"
  name: tradfri_plug_04_power
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_plug_04"
  json_attributes_topic: "zigbee2mqtt/tradfri_plug_04"
  command_topic: "zigbee2mqtt/tradfri_plug_04/set"
  value_template: "{{ value_json.state }}"
- platform: "mqtt"
  name: tradfri_plug_05_power
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_plug_05"
  json_attributes_topic: "zigbee2mqtt/tradfri_plug_05"
  command_topic: "zigbee2mqtt/tradfri_plug_05/set"
  value_template: "{{ value_json.state }}"
- platform: "mqtt"
  name: tradfri_plug_06_power
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_plug_06"
  json_attributes_topic: "zigbee2mqtt/tradfri_plug_06"
  command_topic: "zigbee2mqtt/tradfri_plug_06/set"
  value_template: "{{ value_json.state }}"
- platform: "mqtt"
  name: tradfri_plug_07_power
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_plug_07"
  json_attributes_topic: "zigbee2mqtt/tradfri_plug_07"
  command_topic: "zigbee2mqtt/tradfri_plug_07/set"
  value_template: "{{ value_json.state }}"
- platform: "mqtt"
  name: tradfri_plug_08_power
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_plug_08"
  json_attributes_topic: "zigbee2mqtt/tradfri_plug_08"
  command_topic: "zigbee2mqtt/tradfri_plug_08/set"
  value_template: "{{ value_json.state }}"
- platform: "mqtt"
  name: tradfri_plug_09_power
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_plug_09"
  json_attributes_topic: "zigbee2mqtt/tradfri_plug_09"
  command_topic: "zigbee2mqtt/tradfri_plug_09/set"
  value_template: "{{ value_json.state }}"
- platform: "mqtt"
  name: tradfri_plug_10_power
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_plug_10"
  json_attributes_topic: "zigbee2mqtt/tradfri_plug_10"
  command_topic: "zigbee2mqtt/tradfri_plug_10/set"
  value_template: "{{ value_json.state }}"
- platform: "mqtt"
  name: fibaro_switch_01_switch
  icon: "mdi:flash"
  state_topic: "zwave2mqtt/fibaro_switch_01/37/1/0"
  command_topic: "zwave2mqtt/fibaro_switch_01/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: fibaro_switch_01_switch
  device: {
    "identifiers": [
        "zwave2mqtt_fibaro_switch_01"
      ],
    "manufacturer": "FIBARO System",
    "model": "0x1001",
    "name": "FGWPE/F Wall Plug Gen5",
    "sw_version": "3.02"
  }
- platform: "mqtt"
  name: telldus_switch_01_switch
  icon: "mdi:flash"
  state_topic: "zwave2mqtt/telldus_switch_01/37/1/0"
  command_topic: "zwave2mqtt/telldus_switch_01/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: telldus_switch_01_switch
  device: {
    "identifiers": [
        "zwave2mqtt_telldus_switch_01"
      ],
    "manufacturer": "Telldus",
    "model": "313510",
    "name": "TZWP-102 Plug-in Switch",
    "sw_version": "2.11"
  }
- platform: "mqtt"
  name: telldus_switch_02_switch
  icon: "mdi:flash"
  state_topic: "zwave2mqtt/telldus_switch_02/37/1/0"
  command_topic: "zwave2mqtt/telldus_switch_02/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: telldus_switch_02_switch
  device: {
    "identifiers": [
        "zwave2mqtt_telldus_switch_02"
      ],
    "manufacturer": "Telldus",
    "model": "313510",
    "name": "TZWP-102 Plug-in Switch",
    "sw_version": "2.11"
  }
# - platform: "mqtt"
#   name: telldus_switch_03_switch
#   icon: "mdi:flash"
#   state_topic: "zwave2mqtt/telldus_switch_03/37/1/0"
#   command_topic: "zwave2mqtt/telldus_switch_03/37/1/0/set"
#   value_template: "{{value}}"
#   payload_off: "false"
#   payload_on: "true"
#   unique_id: telldus_switch_03_switch
#   device: {
#     "identifiers": [
#         "zwave2mqtt_telldus_switch_03"
#       ],
#     "manufacturer": "Telldus",
#     "model": "313510",
#     "name": "TZWP-102 Plug-in Switch",
#     "sw_version": "2.11"
#   }
- platform: "mqtt"
  name: telldus_switch_04_switch
  icon: "mdi:flash"
  state_topic: "zwave2mqtt/telldus_switch_04/37/1/0"
  command_topic: "zwave2mqtt/telldus_switch_04/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: telldus_switch_04_switch
  device: {
    "identifiers": [
        "zwave2mqtt_telldus_switch_04"
      ],
    "manufacturer": "Telldus",
    "model": "313510",
    "name": "TZWP-102 Plug-in Switch",
    "sw_version": "2.12"
  }
- platform: "mqtt"
  name: telldus_switch_05_switch
  icon: "mdi:flash"
  state_topic: "zwave2mqtt/telldus_switch_05/37/1/0"
  command_topic: "zwave2mqtt/telldus_switch_05/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: telldus_switch_05_switch
  device: {
    "identifiers": [
        "zwave2mqtt_telldus_switch_05"
      ],
    "manufacturer": "Telldus",
    "model": "313510",
    "name": "TZWP-102 Plug-in Switch",
    "sw_version": "2.12"
  }
- platform: "mqtt"
  name: telldus_switch_06_switch
  state_topic: "zwave2mqtt/telldus_switch_06/37/1/0"
  command_topic: "zwave2mqtt/telldus_switch_06/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: telldus_switch_06_switch
  device: {
    "identifiers": [
        "zwave2mqtt_telldus_switch_06"
      ],
    "manufacturer": "Telldus",
    "model": "313510",
    "name": "TZWP-102 Plug-in Switch",
    "sw_version": "2.12"
  }
- platform: "mqtt"
  name: telldus_switch_07_switch
  state_topic: "zwave2mqtt/telldus_switch_07/37/1/0"
  command_topic: "zwave2mqtt/telldus_switch_07/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: telldus_switch_07_light
  device: {
    "identifiers": [
        "zwave2mqtt_telldus_switch_07"
      ],
    "manufacturer": "Telldus",
    "model": "313510",
    "name": "TZWP-102 Plug-in Switch",
    "sw_version": "2.12"
  }


# Light Controls
- platform: "mqtt"
  name: ha_lights_manual_control
  state_topic: "hass/lights/manual-control"
  command_topic: "hass/lights/manual-control"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"

- platform: "mqtt"
  name: ha_lights_mode_morning
  state_topic: "hass/lights/mode/morning"
  command_topic: "hass/lights/mode"
  value_template: "{{value}}"
  state_on: "true"
  state_off: "false"
  payload_on: "morning"
  payload_off: "morning"
  retain: "on"

- platform: "mqtt"
  name: ha_lights_mode_afternoon
  state_topic: "hass/lights/mode/afternoon"
  command_topic: "hass/lights/mode"
  value_template: "{{value}}"
  state_on: "true"
  state_off: "false"
  payload_on: "afternoon"
  payload_off: "afternoon"
  retain: "on"

- platform: "mqtt"
  name: ha_lights_mode_evening
  state_topic: "hass/lights/mode/evening"
  command_topic: "hass/lights/mode"
  value_template: "{{value}}"
  state_on: "true"
  state_off: "false"
  payload_on: "evening"
  payload_off: "evening"
  retain: "on"

- platform: "mqtt"
  name: ha_lights_mode_night
  state_topic: "hass/lights/mode/night"
  command_topic: "hass/lights/mode"
  value_template: "{{value}}"
  state_on: "true"
  state_off: "false"
  payload_on: "night"
  payload_off: "night"
  retain: "on"


# Light Switches
- platform: "mqtt"
  name: light_bathroom
  state_topic: "hass/lights/bathroom"
  command_topic: "hass/lights/bathroom"
  retain: "on"
- platform: "mqtt"
  name: light_bedroom
  state_topic: "hass/lights/bedroom"
  command_topic: "hass/lights/bedroom"
  retain: "on"
- platform: "mqtt"
  name: light_gallery
  state_topic: "hass/lights/gallery"
  command_topic: "hass/lights/gallery"
  retain: "on"
- platform: "mqtt"
  name: light_kitchen
  state_topic: "hass/lights/kitchen"
  command_topic: "hass/lights/kitchen"
  retain: "on"
- platform: "mqtt"
  name: light_livingroom
  state_topic: "hass/lights/livingroom"
  command_topic: "hass/lights/livingroom"
  retain: "on"
- platform: "mqtt"
  name: light_store
  state_topic: "hass/lights/store"
  command_topic: "hass/lights/store"
  retain: "on"
