title: Frösunda
views:
  # Main
  - !include lovelace/home.yaml

  # Entity Types
  - !include lovelace/lights-all.yaml
  - !include lovelace/entities-battery.yaml
  - !include lovelace/entities-network.yaml
  - !include lovelace/entities-link-quality.yaml
  - !include lovelace/entities-power.yaml

  # Rooms
  - !include lovelace/room-bathroom.yaml
  - !include lovelace/room-bedroom.yaml
  - !include lovelace/room-gallery.yaml
  - !include lovelace/room-kitchen.yaml
  - !include lovelace/room-livingroom.yaml
  - !include lovelace/room-store.yaml

  # Hidden Items
  # # Floorplans
  # - !include lovelace/floorplan-home-lights.yaml
  # - !include lovelace/floorplan-bedroom.yaml

  ## Kitchen
  - !include lovelace/power-kitchen-fridge.yaml
  - !include lovelace/power-kitchen-microwave.yaml
  - !include lovelace/power-kitchen-toaster.yaml
  - !include lovelace/power-kitchen-dishwasher.yaml
  ## Living Room
  - !include lovelace/power-livingroom-jain10.yaml
  - !include lovelace/power-livingroom-jain56.yaml
  - !include lovelace/power-livingroom-tv.yaml
  - !include lovelace/power-livingroom-studytable.yaml
  - !include lovelace/power-livingroom-misc.yaml
