title: Frösunda
views:
  # Main
  - !include lovelace/home.yaml
  - !include lovelace/test.yaml

  # Entity Types
  - !include lovelace/entities-lights.yaml
  # - !include lovelace/entities-lights-triggers.yaml
  - !include lovelace/entities-sensors.yaml
  - !include lovelace/entities-alarms.yaml
  - !include lovelace/entities-devices.yaml
  - !include lovelace/entities-battery.yaml
  - !include lovelace/entities-network.yaml
  - !include lovelace/entities-link-quality.yaml
  - !include lovelace/entities-power.yaml
  - !include lovelace/entities-updates.yaml

  # Devices
  - !include lovelace/device-jain10.yaml
  - !include lovelace/device-jain70.yaml

  # Rooms
  - !include lovelace/room-bathroom.yaml
  - !include lovelace/room-bedroom.yaml
  - !include lovelace/room-gallery.yaml
  - !include lovelace/room-kitchen.yaml
  - !include lovelace/room-livingroom.yaml
  - !include lovelace/room-store.yaml

  # Hidden Items
  # # Floorplans
  # - !include lovelace/floorplan-home-lights.yaml
  # - !include lovelace/floorplan-bedroom.yaml

  #plugs
  ## TP-Link
  - !include lovelace/power-tplink-plug-01.yaml
  - !include lovelace/power-tplink-plug-02.yaml
  ## Fibaro
  - !include lovelace/power-fibaro-plug-01.yaml
  - !include lovelace/power-fibaro-plug-02.yaml
  ## Telldus
  - !include lovelace/power-telldus-plug-01.yaml
  - !include lovelace/power-telldus-plug-02.yaml
  - !include lovelace/power-telldus-plug-03.yaml
  - !include lovelace/power-telldus-plug-04.yaml
  - !include lovelace/power-telldus-plug-05.yaml
  - !include lovelace/power-telldus-plug-06.yaml
  - !include lovelace/power-telldus-plug-07.yaml

  # Details
  - !include lovelace/detail-printer-ender3.yaml
