- platform: "mqtt"
  name: all
  state_topic: "zigbee2mqtt/lights_all"
  availability_topic: "zigbee2mqtt/bridge/state"
  command_topic: "zigbee2mqtt/lights_all/set"
  brightness: true
  color_temp: true
  schema: "json"


- platform: "mqtt"
  name: bathroom
  state_topic: "zigbee2mqtt/lights_bathroom"
  availability_topic: "zigbee2mqtt/bridge/state"
  command_topic: "zigbee2mqtt/lights_bathroom/set"
  brightness: true
  color_temp: true
  schema: "json"


- platform: group
  name: bedroom
  entities:
  - light.bedroom_ceiling
  - light.bedroom_bed
  # - light.telldus_switch_07_light

- platform: "mqtt"
  name: bedroom_ceiling
  state_topic: "zigbee2mqtt/lights_bedroom_ceiling"
  availability_topic: "zigbee2mqtt/bridge/state"
  command_topic: "zigbee2mqtt/lights_bedroom_ceiling/set"
  brightness: true
  color_temp: true
  schema: "json"

- platform: "mqtt"
  name: bedroom_bed
  state_topic: "zigbee2mqtt/lights_bedroom_bed"
  availability_topic: "zigbee2mqtt/bridge/state"
  command_topic: "zigbee2mqtt/lights_bedroom_bed/set"
  brightness: true
  xy: true
  schema: "json"


- platform: "mqtt"
  name: gallery
  state_topic: "zigbee2mqtt/lights_gallery"
  availability_topic: "zigbee2mqtt/bridge/state"
  command_topic: "zigbee2mqtt/lights_gallery/set"
  brightness: true
  color_temp: true
  schema: "json"


- platform: "mqtt"
  name: kitchen
  state_topic: "zigbee2mqtt/lights_kitchen"
  availability_topic: "zigbee2mqtt/bridge/state"
  command_topic: "zigbee2mqtt/lights_kitchen/set"
  brightness: true
  color_temp: true
  schema: "json"


- platform: mqtt
  name: livingroom
  state_topic: zigbee2mqtt/lights_livingroom
  availability_topic: zigbee2mqtt/bridge/state
  command_topic: zigbee2mqtt/lights_livingroom/set
  brightness: true
  xy: true
  schema: json


- platform: "mqtt"
  name: store
  state_topic: "zigbee2mqtt/lights_store"
  availability_topic: "zigbee2mqtt/bridge/state"
  command_topic: "zigbee2mqtt/lights_store/set"
  brightness: true
  color_temp: true
  schema: "json"
