# Groups
- platform: group
  name: all
  entities:
    - light.bathroom
    - light.bedroom
    - light.gallery
    - light.kitchen
    - light.livingroom
    - light.tradfri_plug_01_light
    - light.store


- platform: group
  name: bathroom
  entities:
  - light.tradfri_led_rgb_03_light


- platform: group
  name: bedroom
  entities:
  - light.bedroom_ceiling
  - light.bedroom_bed
  # - light.telldus_switch_07_light

- platform: "mqtt"
  name: bedroom_ceiling
  state_topic: "zigbee2mqtt/lights_bedroom_ceiling"
  availability_topic: "zigbee2mqtt/bridge/state"
  command_topic: "zigbee2mqtt/lights_bedroom_ceiling/set"
  brightness: true
  color_temp: true
  schema: "json"

- platform: "mqtt"
  name: bedroom_bed
  state_topic: "zigbee2mqtt/lights_bedroom_bed"
  availability_topic: "zigbee2mqtt/bridge/state"
  command_topic: "zigbee2mqtt/lights_bedroom_bed/set"
  brightness: true
  xy: true
  schema: "json"


- platform: "mqtt"
  name: gallery
  state_topic: "zigbee2mqtt/lights_gallery"
  availability_topic: "zigbee2mqtt/bridge/state"
  command_topic: "zigbee2mqtt/lights_gallery/set"
  brightness: true
  color_temp: true
  schema: "json"


- platform: "mqtt"
  name: kitchen
  state_topic: "zigbee2mqtt/lights_kitchen"
  availability_topic: "zigbee2mqtt/bridge/state"
  command_topic: "zigbee2mqtt/lights_kitchen/set"
  brightness: true
  color_temp: true
  schema: "json"


- platform: mqtt
  name: livingroom
  state_topic: zigbee2mqtt/lights_livingroom
  availability_topic: zigbee2mqtt/bridge/state
  command_topic: zigbee2mqtt/lights_livingroom/set
  brightness: true
  xy: true
  schema: json


- platform: group
  name: store
  entities:
  - light.tradfri_led_white_03_light
