# White GU10
- platform: "mqtt"
  name: tradfri_led_gu10_01_light
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_led_gu10_01"
  json_attributes_topic: "zigbee2mqtt/tradfri_led_gu10_01"
  command_topic: "zigbee2mqtt/tradfri_led_gu10_01/set"
  brightness: true
  color_temp: true
  schema: "json"
- platform: "mqtt"
  name: tradfri_led_gu10_02_light
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_led_gu10_02"
  json_attributes_topic: "zigbee2mqtt/tradfri_led_gu10_02"
  command_topic: "zigbee2mqtt/tradfri_led_gu10_02/set"
  brightness: true
  color_temp: true
  schema: "json"
- platform: "mqtt"
  name: tradfri_led_gu10_03_light
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_led_gu10_03"
  json_attributes_topic: "zigbee2mqtt/tradfri_led_gu10_03"
  command_topic: "zigbee2mqtt/tradfri_led_gu10_03/set"
  brightness: true
  color_temp: true
  schema: "json"
- platform: "mqtt"
  name: tradfri_led_gu10_04_light
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_led_gu10_04"
  json_attributes_topic: "zigbee2mqtt/tradfri_led_gu10_04"
  command_topic: "zigbee2mqtt/tradfri_led_gu10_04/set"
  brightness: true
  color_temp: true
  schema: "json"
- platform: "mqtt"
  name: tradfri_led_gu10_05_light
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_led_gu10_05"
  json_attributes_topic: "zigbee2mqtt/tradfri_led_gu10_05"
  command_topic: "zigbee2mqtt/tradfri_led_gu10_05/set"
  brightness: true
  color_temp: true
  schema: "json"
- platform: "mqtt"
  name: tradfri_led_gu10_06_light
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_led_gu10_06"
  json_attributes_topic: "zigbee2mqtt/tradfri_led_gu10_06"
  command_topic: "zigbee2mqtt/tradfri_led_gu10_06/set"
  brightness: true
  color_temp: true
  schema: "json"
