# RGB E27
- platform: "mqtt"
  name: tradfri_led_rgb_01_light
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_led_rgb_01"
  json_attributes_topic: "zigbee2mqtt/tradfri_led_rgb_01"
  command_topic: "zigbee2mqtt/tradfri_led_rgb_01/set"
  brightness: true
  xy: true
  schema: "json"
- platform: "mqtt"
  name: tradfri_led_rgb_02_light
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_led_rgb_02"
  json_attributes_topic: "zigbee2mqtt/tradfri_led_rgb_02"
  command_topic: "zigbee2mqtt/tradfri_led_rgb_02/set"
  brightness: true
  xy: true
  schema: "json"
- platform: "mqtt"
  name: tradfri_led_rgb_03_light
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_led_rgb_03"
  json_attributes_topic: "zigbee2mqtt/tradfri_led_rgb_03"
  command_topic: "zigbee2mqtt/tradfri_led_rgb_03/set"
  brightness: true
  xy: true
  schema: "json"
- platform: "mqtt"
  name: tradfri_led_rgb_04_light
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_led_rgb_04"
  json_attributes_topic: "zigbee2mqtt/tradfri_led_rgb_04"
  command_topic: "zigbee2mqtt/tradfri_led_rgb_04/set"
  brightness: true
  xy: true
  schema: "json"
- platform: "mqtt"
  name: tradfri_led_rgb_05_light
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_led_rgb_05"
  json_attributes_topic: "zigbee2mqtt/tradfri_led_rgb_05"
  command_topic: "zigbee2mqtt/tradfri_led_rgb_05/set"
  brightness: true
  xy: true
  schema: "json"
