# White E27
- platform: "mqtt"
  name: tradfri_led_white_01_light
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_led_white_01"
  json_attributes_topic: "zigbee2mqtt/tradfri_led_white_01"
  command_topic: "zigbee2mqtt/tradfri_led_white_01/set"
  brightness: true
  color_temp: true
  schema: "json"
- platform: "mqtt"
  name: tradfri_led_white_02_light
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_led_white_02"
  json_attributes_topic: "zigbee2mqtt/tradfri_led_white_02"
  command_topic: "zigbee2mqtt/tradfri_led_white_02/set"
  brightness: true
  color_temp: true
  schema: "json"
- platform: "mqtt"
  name: tradfri_led_white_03_light
  availability_topic: "zigbee2mqtt/bridge/state"
  state_topic: "zigbee2mqtt/tradfri_led_white_03"
  json_attributes_topic: "zigbee2mqtt/tradfri_led_white_03"
  command_topic: "zigbee2mqtt/tradfri_led_white_03/set"
  brightness: true
  color_temp: true
  schema: "json"
