# Battery Levels
- platform: "mqtt"
  name: aeotec_sensor6_01_battery
  state_topic: "zwave2mqtt/aeotec_sensor6_01/128/1/0"
  unit_of_measurement: "%"
  value_template: "{{value}}"
  device_class: "battery"
  state_class: measurement
  unique_id: aeotec_sensor6_01_battery
