# Battery Levels
- platform: template
  sensors:
# Remotes
    tradfri_switch_01_battery:
      device_class: battery
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.tradfri_switch_01_action', 'battery') }}"
    tradfri_switch_02_battery:
      device_class: battery
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.tradfri_switch_02_action', 'battery') }}"
    tradfri_button_01_battery:
      device_class: battery
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.tradfri_button_01_action', 'battery') }}"
    tradfri_button_02_battery:
      device_class: battery
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.tradfri_button_02_action', 'battery') }}"
    tradfri_button_03_battery:
      device_class: battery
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.tradfri_button_03_action', 'battery') }}"
    tradfri_button_04_battery:
      device_class: battery
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.tradfri_button_04_action', 'battery') }}"
    tradfri_button_05_battery:
      device_class: battery
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.tradfri_button_05_action', 'battery') }}"
    tradfri_button_06_battery:
      device_class: battery
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.tradfri_button_06_action', 'battery') }}"
    tradfri_button_07_battery:
      device_class: battery
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.tradfri_button_07_action', 'battery') }}"
    tradfri_button_08_battery:
      device_class: battery
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.tradfri_button_08_action', 'battery') }}"
# Door Sensors
    aqara_sensor_switch_01_battery:
      device_class: battery
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.aqara_sensor_switch_01_contact', 'battery') }}"
# Motion Sensors
    tradfri_motion_01_battery:
      device_class: battery
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.tradfri_motion_01_occupancy', 'battery') }}"
    smartthings_motion_temp_01_battery:
      value_template: "{{ state_attr('binary_sensor.smartthings_motion_temp_01_occupancy', 'battery') }}"
      device_class: battery
    smartthings_motion_temp_02_battery:
      device_class: battery
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.smartthings_motion_temp_02_occupancy', 'battery') }}"
- platform: "mqtt"
  name: aeotec_sensor6_01_battery
  state_topic: "zwave2mqtt/aeotec_sensor6_01/128/1/0"
  unit_of_measurement: "%"
  value_template: "{{value}}"
  device_class: "battery"
  state_class: measurement
  unique_id: aeotec_sensor6_01_battery
