# Power
- platform: "mqtt"
  name: fibaro_switch_01_power
  state_topic: "zwave2mqtt/fibaro_switch_01/49/1/4"
  unit_of_measurement: "W"
  value_template: "{{value}}"
  device_class: "power"
  unique_id: fibaro_switch_01_power
- platform: "mqtt"
  name: fibaro_switch_02_power
  state_topic: "zwave2mqtt/fibaro_switch_02/49/1/4"
  unit_of_measurement: "W"
  value_template: "{{value}}"
  device_class: "power"
  unique_id: fibaro_switch_02_power



# Energy
- platform: "mqtt"
  name: fibaro_switch_01_energy
  icon: mdi:power-plug
  state_topic: "zwave2mqtt/fibaro_switch_01/50/1/0"
  unit_of_measurement: "kWh"
  value_template: "{{value}}"
  # device_class: "None"
  unique_id: fibaro_switch_01_energy
- platform: "mqtt"
  name: fibaro_switch_02_energy
  icon: mdi:power-plug
  state_topic: "zwave2mqtt/fibaro_switch_02/50/1/0"
  unit_of_measurement: "kWh"
  value_template: "{{value}}"
  # device_class: "None"
  unique_id: fibaro_switch_02_energy
