# Humidity
- platform: "mqtt"
  name: aeotec_sensor6_01_humidity
  state_topic: "zwave2mqtt/aeotec_sensor6_01/49/1/5"
  unit_of_measurement: "%"
  value_template: "{{value}}"
  device_class: "humidity"
  state_class: measurement
  unique_id: aeotec_sensor6_01_humidity
