# 5 button remotes
- platform: "mqtt"
  name: tradfri_switch_01_action
  state_topic: "zigbee2mqtt/tradfri_switch_01"
  json_attributes_topic: "zigbee2mqtt/tradfri_switch_01"
  availability_topic: "zigbee2mqtt/bridge/state"
  value_template: "{{ value_json.action}}"
  icon: mdi:gesture-double-tap
- platform: "mqtt"
  name: tradfri_switch_02_action
  state_topic: "zigbee2mqtt/tradfri_switch_02"
  json_attributes_topic: "zigbee2mqtt/tradfri_switch_02"
  availability_topic: "zigbee2mqtt/bridge/state"
  value_template: "{{ value_json.action}}"
  icon: mdi:gesture-double-tap
