# Lights
- platform: "mqtt"
  name: ha_lights_mode
  state_topic: "hass/lights/mode"
  value_template: "{{value}}"



# Motion & Vibration
- platform: "mqtt"
  name: aeotec_sensor6_01_motion_vibration
  state_topic: "zwave2mqtt/aeotec_sensor6_01/48/1/0"
  unit_of_measurement: ""
  value_template: "{{value}}"
  unique_id: aeotec_sensor6_01_motion_vibration
