# Power
- platform: "mqtt"
  name: telldus_switch_01_power
  icon: "mdi:flash"
  state_topic: "zwave2mqtt/telldus_switch_01/50/1/2"
  unit_of_measurement: "W"
  value_template: "{{value}}"
  device_class: "power"
  unique_id: telldus_switch_01_power
- platform: "mqtt"
  name: telldus_switch_02_power
  icon: "mdi:flash"
  state_topic: "zwave2mqtt/telldus_switch_02/50/1/2"
  unit_of_measurement: "W"
  value_template: "{{value}}"
  device_class: "power"
  unique_id: telldus_switch_02_power
- platform: "mqtt"
  name: telldus_switch_03_power
  icon: "mdi:flash"
  state_topic: "zwave2mqtt/telldus_switch_03/50/1/2"
  unit_of_measurement: "W"
  value_template: "{{value}}"
  device_class: "power"
  unique_id: telldus_switch_03_power
- platform: "mqtt"
  name: telldus_switch_04_power
  icon: "mdi:flash"
  state_topic: "zwave2mqtt/telldus_switch_04/50/1/2"
  unit_of_measurement: "W"
  value_template: "{{value}}"
  device_class: "power"
  unique_id: telldus_switch_04_power
- platform: "mqtt"
  name: telldus_switch_05_power
  icon: "mdi:flash"
  state_topic: "zwave2mqtt/telldus_switch_05/50/1/2"
  unit_of_measurement: "W"
  value_template: "{{value}}"
  device_class: "power"
  unique_id: telldus_switch_05_power
- platform: "mqtt"
  name: telldus_switch_06_power
  icon: "mdi:flash"
  state_topic: "zwave2mqtt/telldus_switch_06/50/1/2"
  unit_of_measurement: "W"
  value_template: "{{value}}"
  device_class: "power"
  unique_id: telldus_switch_06_power
- platform: "mqtt"
  name: telldus_switch_07_power
  icon: "mdi:flash"
  state_topic: "zwave2mqtt/telldus_switch_07/50/1/2"
  unit_of_measurement: "W"
  value_template: "{{value}}"
  device_class: "power"
  unique_id: telldus_switch_07_power



# Energy
- platform: "mqtt"
  name: telldus_switch_01_energy
  icon: "mdi:flash-circle"
  state_topic: "zwave2mqtt/telldus_switch_01/50/1/0"
  unit_of_measurement: "kWh"
  value_template: "{{value}}"
  # device_class: "None"
  unique_id: telldus_switch_01_energy
- platform: "mqtt"
  name: telldus_switch_02_energy
  icon: "mdi:flash-circle"
  state_topic: "zwave2mqtt/telldus_switch_02/50/1/0"
  unit_of_measurement: "kWh"
  value_template: "{{value}}"
  # device_class: "None"
  unique_id: telldus_switch_02_energy
- platform: "mqtt"
  name: telldus_switch_03_energy
  icon: "mdi:flash-circle"
  state_topic: "zwave2mqtt/telldus_switch_03/50/1/0"
  unit_of_measurement: "kWh"
  value_template: "{{value}}"
  # device_class: "None"
  unique_id: telldus_switch_03_energy
- platform: "mqtt"
  name: telldus_switch_04_energy
  icon: "mdi:flash-circle"
  state_topic: "zwave2mqtt/telldus_switch_04/50/1/0"
  unit_of_measurement: "kWh"
  value_template: "{{value}}"
  unique_id: telldus_switch_04_energy
- platform: "mqtt"
  name: telldus_switch_05_energy
  icon: "mdi:flash-circle"
  state_topic: "zwave2mqtt/telldus_switch_05/50/1/0"
  unit_of_measurement: "kWh"
  value_template: "{{value}}"
  unique_id: telldus_switch_05_energy
- platform: "mqtt"
  name: telldus_switch_06_energy
  icon: "mdi:flash-circle"
  state_topic: "zwave2mqtt/telldus_switch_06/50/1/0"
  unit_of_measurement: "kWh"
  value_template: "{{value}}"
  unique_id: telldus_switch_06_energy
- platform: "mqtt"
  name: telldus_switch_07_energy
  icon: "mdi:flash-circle"
  state_topic: "zwave2mqtt/telldus_switch_07/50/1/0"
  unit_of_measurement: "kWh"
  value_template: "{{value}}"
  unique_id: telldus_switch_07_energy



# Voltage
- platform: "mqtt"
  name: telldus_switch_01_voltage
  icon: "mdi:flash-circle"
  state_topic: "zwave2mqtt/telldus_switch_01/50/1/4"
  unit_of_measurement: "V"
  value_template: "{{value}}"
  # device_class: "None"
  unique_id: telldus_switch_01_voltage
- platform: "mqtt"
  name: telldus_switch_02_voltage
  icon: "mdi:flash-circle"
  state_topic: "zwave2mqtt/telldus_switch_02/50/1/4"
  unit_of_measurement: "V"
  value_template: "{{value}}"
  # device_class: "None"
  unique_id: telldus_switch_02_voltage
- platform: "mqtt"
  name: telldus_switch_03_voltage
  icon: "mdi:flash-circle"
  state_topic: "zwave2mqtt/telldus_switch_03/50/1/4"
  unit_of_measurement: "V"
  value_template: "{{value}}"
  # device_class: "None"
  unique_id: telldus_switch_03_voltage
- platform: "mqtt"
  name: telldus_switch_04_voltage
  icon: "mdi:flash-circle"
  state_topic: "zwave2mqtt/telldus_switch_04/50/1/4"
  unit_of_measurement: "V"
  value_template: "{{value}}"
  unique_id: telldus_switch_04_voltage
- platform: "mqtt"
  name: telldus_switch_05_voltage
  icon: "mdi:flash-circle"
  state_topic: "zwave2mqtt/telldus_switch_05/50/1/4"
  unit_of_measurement: "V"
  value_template: "{{value}}"
  unique_id: telldus_switch_05_voltage
- platform: "mqtt"
  name: telldus_switch_06_voltage
  icon: "mdi:flash-circle"
  state_topic: "zwave2mqtt/telldus_switch_06/50/1/4"
  unit_of_measurement: "V"
  value_template: "{{value}}"
  unique_id: telldus_switch_06_voltage
- platform: "mqtt"
  name: telldus_switch_07_voltage
  icon: "mdi:flash-circle"
  state_topic: "zwave2mqtt/telldus_switch_07/50/1/4"
  unit_of_measurement: "V"
  value_template: "{{value}}"
  unique_id: telldus_switch_07_voltage



  # Current
- platform: "mqtt"
  name: telldus_switch_01_current
  icon: "mdi:flash-circle"
  state_topic: "zwave2mqtt/telldus_switch_01/50/1/5"
  unit_of_measurement: "A"
  value_template: "{{value}}"
  # device_class: "None"
  unique_id: telldus_switch_01_current
- platform: "mqtt"
  name: telldus_switch_02_current
  icon: "mdi:flash-circle"
  state_topic: "zwave2mqtt/telldus_switch_02/50/1/5"
  unit_of_measurement: "A"
  value_template: "{{value}}"
  # device_class: "None"
  unique_id: telldus_switch_02_current
- platform: "mqtt"
  name: telldus_switch_03_current
  icon: "mdi:flash-circle"
  state_topic: "zwave2mqtt/telldus_switch_03/50/1/5"
  unit_of_measurement: "A"
  value_template: "{{value}}"
  # device_class: "None"
  unique_id: telldus_switch_03_current
- platform: "mqtt"
  name: telldus_switch_04_current
  icon: "mdi:flash-circle"
  state_topic: "zwave2mqtt/telldus_switch_04/50/1/5"
  unit_of_measurement: "A"
  value_template: "{{value}}"
  unique_id: telldus_switch_04_current
- platform: "mqtt"
  name: telldus_switch_05_current
  icon: "mdi:flash-circle"
  state_topic: "zwave2mqtt/telldus_switch_05/50/1/5"
  unit_of_measurement: "A"
  value_template: "{{value}}"
  unique_id: telldus_switch_05_current
- platform: "mqtt"
  name: telldus_switch_06_current
  icon: "mdi:flash-circle"
  state_topic: "zwave2mqtt/telldus_switch_06/50/1/5"
  unit_of_measurement: "A"
  value_template: "{{value}}"
  unique_id: telldus_switch_06_current
- platform: "mqtt"
  name: telldus_switch_07_current
  icon: "mdi:flash-circle"
  state_topic: "zwave2mqtt/telldus_switch_07/50/1/5"
  unit_of_measurement: "A"
  value_template: "{{value}}"
  unique_id: telldus_switch_07_current
