# Temperature
- platform: "mqtt"
  name: aeotec_sensor6_01_temperature
  state_topic: "zwave2mqtt/aeotec_sensor6_01/49/1/1"
  unit_of_measurement: "°C"
  value_template: "{{value}}"
  device_class: "temperature"
  state_class: measurement
  unique_id: aeotec_sensor6_01_temperature
