# TP-Link Plugs
- platform: template
  sensors:
    # TP-Link Plug #1
    tplink_plug_01_amps:
      friendly_name_template: "{{ states.switch.tplink_plug_01.name}} Current"
      value_template: '{{ states.switch.tplink_plug_01.attributes["current_a"] | float }}'
      unit_of_measurement: 'A'
      device_class: current
    tplink_plug_01_watts:
      friendly_name_template: "{{ states.switch.tplink_plug_01.name}} Current Consumption"
      value_template: '{{ states.switch.tplink_plug_01.attributes["current_power_w"] | float }}'
      unit_of_measurement: 'W'
      device_class: power
    tplink_plug_01_total_kwh:
      friendly_name_template: "{{ states.switch.tplink_plug_01.name}} Total Consumption"
      value_template: '{{ states.switch.tplink_plug_01.attributes["total_energy_kwh"] | float }}'
      unit_of_measurement: 'kWh'
      device_class: energy
    tplink_plug_01_volts:
      friendly_name_template: "{{ states.switch.tplink_plug_01.name}} Voltage"
      value_template: '{{ states.switch.tplink_plug_01.attributes["voltage"] | float }}'
      unit_of_measurement: 'V'
      device_class: voltage
    tplink_plug_01_today_kwh:
      friendly_name_template: "{{ states.switch.tplink_plug_01.name}} Today's Consumption"
      value_template: '{{ states.switch.tplink_plug_01.attributes["today_energy_kwh"] | float }}'
      unit_of_measurement: 'kWh'
      device_class: energy
    # TP-Link Plug #2
    tplink_plug_02_amps:
      friendly_name_template: "{{ states.switch.tplink_plug_02.name}} Current"
      value_template: '{{ states.switch.tplink_plug_02.attributes["current_a"] | float }}'
      unit_of_measurement: 'A'
      device_class: current
    tplink_plug_02_watts:
      friendly_name_template: "{{ states.switch.tplink_plug_02.name}} Current Consumption"
      value_template: '{{ states.switch.tplink_plug_02.attributes["current_power_w"] | float }}'
      unit_of_measurement: 'W'
      device_class: power
    tplink_plug_02_total_kwh:
      friendly_name_template: "{{ states.switch.tplink_plug_02.name}} Total Consumption"
      value_template: '{{ states.switch.tplink_plug_02.attributes["total_energy_kwh"] | float }}'
      unit_of_measurement: 'kWh'
      device_class: energy
    tplink_plug_02_volts:
      friendly_name_template: "{{ states.switch.tplink_plug_02.name}} Voltage"
      value_template: '{{ states.switch.tplink_plug_02.attributes["voltage"] | float }}'
      unit_of_measurement: 'V'
      device_class: voltage
    tplink_plug_02_today_kwh:
      friendly_name_template: "{{ states.switch.tplink_plug_02.name}} Today's Consumption"
      value_template: '{{ states.switch.tplink_plug_02.attributes["today_energy_kwh"] | float }}'
      unit_of_measurement: 'kWh'
      device_class: energy
