# IOT Link Jain78
- platform: mqtt
  name: "Jain78 - Connected"
  state_topic: "iotlink/jain/jain78/lwt"
  value_template: "{{ value }}"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: "connectivity"
  qos: 1
- platform: mqtt
  name: "Jain78 - Power Status"
  state_topic: "iotlink/jain/jain78/windows-monitor/stats/power/status"
  value_template: "{{ value }}"
  payload_on: "True"
  payload_off: "False"
  device_class: "plug"
  availability_topic: "iotlink/jain/jain78/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1
- platform: mqtt
  name: "Jain78 - Network Wired"
  state_topic: "iotlink/jain/jain78/windows-monitor/stats/network/1/wired"
  value_template: "{{ value }}"
  payload_on: "True"
  payload_off: "False"
  availability_topic: "iotlink/jain/jain78/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1
