# Aeotec
- platform: template
  sensors:
    aeotec_sensor6_01_motion:
      device_class: motion
      value_template: "{{ states('sensor.aeotec_sensor6_01_motion_vibration') | int == 8}}"
    aeotec_sensor6_01_vibration:
      device_class: vibration
      value_template: "{{ states('sensor.aeotec_sensor6_01_motion_vibration') | int == 3}}"



# Virtual sensors
- platform: template
  sensors:
    light_timers:
      value_template: "{{ is_state('timer.bathroom', 'active')
                        or is_state('timer.bathroom_max', 'active')
                        or is_state('timer.gallery', 'active')
                        or is_state('timer.gallery_max', 'active')
                        or is_state('timer.kitchen', 'active')
                        or is_state('timer.kitchen_max', 'active')
                        or is_state('timer.store_max', 'active')
                        }}"
    motion_state_sensors:
      value_template: "{{ is_state('binary_sensor.aqara_sensor_switch_01_contact', 'on')
                        or is_state('binary_sensor.smartthings_motion_temp_01_occupancy', 'on')
                        or is_state('binary_sensor.smartthings_motion_temp_02_occupancy', 'on')
                        or is_state('binary_sensor.tradfri_motion_01_occupancy', 'on')
                        or is_state('binary_sensor.aeotec_sensor6_01_motion', 'on')
                        }}"

    battery_bicycle_charging:
      value_template: "{{ states('sensor.telldus_switch_06_power') | float > 15.0 }}"

    # light_trigger_bathroom:
      # value_template: "{{ is_state('binary_sensor.tradfri_motion_01_occupancy', 'on') or is_state('binary_sensor.aeotec_sensor6_01_motion', 'on') }}"
    # light_trigger_gallery:
    #   value_template: "{{ is_state('binary_sensor.smartthings_motion_temp_01_occupancy_delayed', 'on') }}"
    # light_trigger_kitchen:
    #   value_template: "{{ is_state('binary_sensor.smartthings_motion_temp_02_occupancy_delayed', 'on') }}"
    # light_trigger_store:
    #   value_template: "{{ is_state('binary_sensor.aqara_sensor_switch_01_contact', 'on') }}"

    packages_active:
      value_template: "{{ ((states('sensor.seventeentrack_packages_delivered') | int) +
                           (states('sensor.seventeentrack_packages_expired') | int) +
                           (states('sensor.seventeentrack_packages_in_transit') | int) +
                           (states('sensor.seventeentrack_packages_not_found') | int) +
                           (states('sensor.seventeentrack_packages_ready_to_be_picked_up') | int) +
                           (states('sensor.seventeentrack_packages_undelivered') | int) +
                           (states('sensor.seventeentrack_packages_delivered') | int)) > 0}}"
