# Motion Sensors
- platform: "mqtt"
  name: smartthings_motion_temp_01_occupancy
  state_topic: "zigbee2mqtt/smartthings_motion_temp_01"
  json_attributes_topic: "zigbee2mqtt/smartthings_motion_temp_01"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.occupancy }}"
  device_class: "motion"
# - platform: "mqtt"
#   name: smartthings_motion_temp_01_occupancy_delayed
#   state_topic: "hass/sensors/smartthings_motion_temp_01"
#   availability_topic: "zigbee2mqtt/bridge/state"
#   payload_on: "true"
#   payload_off: "false"
#   value_template: "{{ value_json.occupancy }}"
#   device_class: "motion"
- platform: "mqtt"
  name: smartthings_motion_temp_02_occupancy
  state_topic: "zigbee2mqtt/smartthings_motion_temp_02"
  json_attributes_topic: "zigbee2mqtt/smartthings_motion_temp_02"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.occupancy }}"
  device_class: "motion"
# - platform: "mqtt"
#   name: smartthings_motion_temp_02_occupancy_delayed
#   state_topic: "hass/sensors/smartthings_motion_temp_02"
#   availability_topic: "zigbee2mqtt/bridge/state"
#   payload_on: "true"
#   payload_off: "false"
#   value_template: "{{ value_json.occupancy }}"
#   device_class: "motion"
- platform: "mqtt"
  name: tradfri_motion_01_occupancy
  state_topic: "zigbee2mqtt/tradfri_motion_01"
  json_attributes_topic: "zigbee2mqtt/tradfri_motion_01"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.occupancy }}"
  device_class: "motion"
