# Connected Devices
- platform: ping
  host: NET01.jain.lan
  name: ping_asus_router242
  count: 1
  scan_interval: 30
- platform: ping
  host: SRV78.jain.lan
  name: ping_jain78
  count: 1
  scan_interval: 30
- platform: ping
  host: SRV01.jain.lan
  name: ping_srv01
  count: 1
  scan_interval: 30
- platform: ping
  host: nas83.jain.lan
  name: ping_nas83
  count: 1
  scan_interval: 30
- platform: ping
  host: jain56.jain.lan
  name: ping_jain56
  count: 1
- platform: ping
  host: docker56.jain.lan
  name: ping_docker56
  count: 1

- platform: ping
  host: jain10.jain.lan
  name: ping_jain10
  count: 1
  scan_interval: 30
- platform: ping
  host: jain70.jain.lan
  name: ping_jain70
  count: 1
- platform: ping
  host: com49.jain.lan
  name: ping_afry
  count: 1
- platform: ping
  host: jain24.jain.lan
  name: ping_jain24
  count: 1

- platform: ping
  host: iot02.jain.lan
  name: ping_octopi
  count: 1
- platform: ping
  host: ha-bridge.jain.lan
  name: ping_raspberrypi_ha_bridge
  count: 1
- platform: ping
  host: raspberrypi.jain.lan
  name: ping_raspberrypi
  count: 1

- platform: ping
  host: mob05.jain.lan
  name: ping_motorola_g6_plus
  count: 1
- platform: ping
  host: mob04.jain.lan
  name: ping_sony_xperia_zr
  count: 1
- platform: ping
  host: mob58.jain.lan
  name: ping_sony_xperia_z1
  count: 1
- platform: ping
  host: mob07.jain.lan
  name: ping_asus_a810
  count: 1
- platform: ping
  host: mob23.jain.lan
  name: ping_google_nexus_10
  count: 1
- platform: ping
  host: mob65.jain.lan
  name: ping_amazon_kindle_fire_7
  count: 1
- platform: ping
  host: jain01.jain.lan
  name: ping_lamina_1010
  count: 1

- platform: ping
  host: med07.jain.lan
  name: ping_chromecast_audio_bedroom
  count: 1
- platform: ping
  host: med08.jain.lan
  name: ping_chromecast_audio_livingroom
  count: 1
- platform: ping
  host: med03.jain.lan
  name: ping_chromecast_video
  count: 1
