#  Switches
- platform: "mqtt"
  name: fibaro_switch_02_switch
  state_topic: "zwave2mqtt/fibaro_switch_02/37/1/0"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: fibaro_switch_02_switch
- platform: "mqtt"
  name: telldus_switch_03_switch
  state_topic: "zwave2mqtt/telldus_switch_03/37/1/0"
  # command_topic: "zwave2mqtt/telldus_switch_03/37/1/0/set"
  value_template: "{{value}}"
  payload_off: "false"
  payload_on: "true"
  unique_id: telldus_switch_03_switch
