blueprint:
  name: Binary Sensor to Light
  description: Turn a light on/off based on motion sensor
  domain: automation

  input:
    motion_entity:
      name: Motion Sensor
      description: An on value means 'motion', an off values means 'no motion'
      selector:
        entity:
          domain: binary_sensor
    target_light:
      name: Light Switch
      description: The light switch of the room
      selector:
        entity:
          domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 5
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: minutes

mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input motion_entity
  from: 'off'
  to: 'on'

variables:
  light_entity: !input target_light

action:
  - choose:
    - conditions: # Check for colour support
      - "{{ is_state(light_entity, 'off') }}"
      sequence:
      - service: script.light_on
        data:
          entity_id: !input target_light
  - wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      from: 'on'
      to: 'off'
  - delay:
      # seconds: !input no_motion_wait  # Testing
      minutes: !input no_motion_wait  # Production
  - service: light.turn_off
    data:
      entity_id: !input target_light
