blueprint:
  name: Light Timer Finished
  description: Turn off light when timer finishes
  domain: automation

  input:
    light_entity:
      name: Light
      description: The light
      selector:
        entity:
          domain: light
    target_timer:
      name: Timer
      description: The timer of the light
      selector:
        entity:
          domain: timer

mode: restart
max_exceeded: silent

trigger:
  platform: event
  event_type: timer.finished
  event_data:
    entity_id: !input target_timer

action:
  - service: light.turn_off
    data:
      entity_id: !input light_entity

