# Decoration Lights
- alias: Light Mode - Decoration Lights - Night
  id: arnav-jain-se_decoration_lights_off
  trigger:
  - platform: state
    entity_id: switch.ha_lights_mode_night
  - platform: state
    entity_id: sun.sun
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: switch.ha_lights_mode_night
          state: 'on'
        - condition: state
          entity_id: sun.sun
          state: 'above_horizon'
  action:
  - service: switch.turn_off
    data:
      entity_id:
        - switch.tradfri_plug_03_power
        - switch.tradfri_plug_04_power
        - switch.tradfri_plug_05_power
        - switch.tradfri_plug_06_power

- alias: Light Mode - Decoration Lights - Daytime darkness
  id: arnav-jain-se_decoration_lights_on
  trigger:
  - platform: state
    entity_id: switch.ha_lights_mode_night
  - platform: state
    entity_id: sun.sun
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: switch.ha_lights_mode_night
          state: 'off'
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
  action:
  - service: switch.turn_on
    data:
      entity_id:
        - switch.tradfri_plug_03_power
        - switch.tradfri_plug_04_power
        - switch.tradfri_plug_05_power
        - switch.tradfri_plug_06_power
