# Lights Mode Time
- alias: Lights Mode - Start Up
  id: arnav-jain-se_timer_lights_mode_starup
  trigger:
    - platform: homeassistant
      event: start
  action:
  - service: script.set_light_mode
  mode: single


- alias: Time - Lights Mode - Morning
  id: arnav-jain-se_time_lights_mode_morning
  trigger:
  - platform: time
    at: input_datetime.lights_morning
  - platform: sun
    event: sunrise
  action:
  - service: switch.turn_on
    entity_id: switch.ha_lights_mode_morning
  mode: single


- alias: Time - Lights Mode - Afternoon
  id: arnav-jain-se_time_lights_mode_afternoon
  trigger:
    platform: time
    at: input_datetime.lights_afternoon
  action:
  - service: switch.turn_on
    entity_id: switch.ha_lights_mode_afternoon
  mode: single


- alias: Time - Lights Mode - Evening
  id: arnav-jain-se_time_lights_mode_evening
  trigger:
    platform: time
    at: input_datetime.lights_evening
  action:
  - service: switch.turn_on
    entity_id: switch.ha_lights_mode_evening
  mode: single


- alias: Time - Lights Mode - Night
  id: arnav-jain-se_timer_lights_mode_night
  trigger:
    platform: time
    at: input_datetime.lights_night
  action:
  - service: switch.turn_on
    entity_id: switch.ha_lights_mode_night
  mode: single




# Lights Mode
- alias: Lights Mode - Morning
  id: arnav-jain-se_lights_mode_morning
  mode: single
  trigger:
  - platform: state
    entity_id: switch.ha_lights_mode_morning
    to: 'on'
  action:
  - service: switch.turn_off
    data:
      entity_id:
        # - switch.ha_lights_mode_morning
        - switch.ha_lights_mode_afternoon
        - switch.ha_lights_mode_evening
        - switch.ha_lights_mode_night
  - service: script.light_mode_change


- alias: Lights Mode - Afternoon
  id: arnav-jain-se_lights_mode_afternoon
  mode: single
  trigger:
  - platform: state
    entity_id: switch.ha_lights_mode_afternoon
    to: 'on'
  action:
  - service: switch.turn_off
    data:
      entity_id:
        - switch.ha_lights_mode_morning
        # - switch.ha_lights_mode_afternoon
        - switch.ha_lights_mode_evening
        - switch.ha_lights_mode_night
  - service: script.light_mode_change


- alias: Lights Mode - Evening
  id: arnav-jain-se_lights_mode_evening
  mode: single
  trigger:
  - platform: state
    entity_id: switch.ha_lights_mode_evening
    to: 'on'
  action:
  - service: switch.turn_off
    data:
      entity_id:
        - switch.ha_lights_mode_morning
        - switch.ha_lights_mode_afternoon
        # - switch.ha_lights_mode_evening
        - switch.ha_lights_mode_night
  - service: script.light_mode_change


- alias: Lights Mode - Night
  id: arnav-jain-se_lights_mode_night
  mode: single
  trigger:
  - platform: state
    entity_id: switch.ha_lights_mode_night
    to: 'on'
  action:
  - service: switch.turn_off
    data:
      entity_id:
        - switch.ha_lights_mode_morning
        - switch.ha_lights_mode_afternoon
        - switch.ha_lights_mode_evening
        # - switch.ha_lights_mode_night
  - service: script.light_mode_change
